name: servana
description: "A new Flutter project."

# لمنع النشر العرضي على pub.dev
publish_to: 'none'

# إعدادات الإصدار (لاندرويد وآي أو إس)
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  # حزم أيقونات وأدوات واجهة المستخدم
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  smooth_page_indicator: ^1.2.1

  # حزم الموقع والخرائط
  geolocator: ^13.0.2

  geocoding: ^3.0.0

  # حزم إدخال البيانات
  intl_phone_field: ^3.2.0
  flutter_rating_bar: ^4.0.1

  # حزم الصلاحيات والتخزين المحلي
  permission_handler: ^12.0.0+1
  shared_preferences: ^2.5.3

  # حزم التعريب الرسمية (بدلاً من الحزم القديمة)
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0

  flutter_secure_storage: ^8.0.0
  firebase_core: ^3.13.0
  firebase_messaging: ^15.2.5
  #


  http: ^1.4.0
  url_launcher: ^6.3.1

#

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.4  # مطلوب لتوليد ملفات التعريب

flutter:
  generate: true  # تمكين توليد ملفات l10n تلقائياً
  uses-material-design: true

  # ملفات الأصول
  assets:
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
